### ISSUE TITLE
Cadastro Institution/Estabelecimento - Prenchimento Automático por CEP

### ISSUE THREAD

**Issue by valdosouza** [valdosouza/webConsignacao#5]
Utilizar um webservice para pesquisar dados do CEP e fazer o preenchimento automático.
EX: https://viacep.com.br/ws/01001000/json/
Utilizar um botão ao lado do campo CEP para fazer isso de forma ativa.

**Comment by Feezyn** [comment]
016eb15 - (HEAD -> feature/cadastro-estabelecimento, origin/feature/cadastro-estabelecimento)
