### ISSUE TITLE
Estrutura de modulos

### ISSUE THREAD

**Issue by thKali** [valdosouza/webConsignacao#64]
Os modulos de registro poderiam ser submodulos de um "Register Module"

**Comment by valdosouza** [comment]
Eu não tratei assim...por que algumas coisas conceituais, que pode te levar a deixar o codigo acoplado.
Um modulo pode ser um conjunto de funções (mas aqui vem o alto acoplamento).
Para mim cada modulo deve tratar de uma responsabilidade (veja sobre o Solid)
e de forma Abstrata você pode criar um Modulo para gerenciar outros, para poder agrupar tarefas correlatas)

ps. espero ter entendido a tua pergunta....
