### ISSUE TITLE
Cadastro Stock/Estoque - Lista

### ISSUE THREAD

**Issue by valdosouza** [valdosouza/webConsignacao#8]
- [x] Domain => entity | repository | usescase
- [x] - Data => Model | DataSource | Repository 
- [x] Presentation => Pages
                         Lista de Estoque contendo nome
                         Criar filtro na mesma tela para filtrar por nome

**Comment by Feezyn** [comment]
(HEAD -> feature/cadastro-estoque, origin/feature/cadastro-estoque) Cadastro Stock/Estoque - Lista #8
