### ISSUE TITLE
Cadastro Stock/Estoque - Registro

### ISSUE THREAD

**Issue by valdosouza** [valdosouza/webConsignacao#9]
Formulário com campo Descrição/Ativo
Operações de CRUD.
Validações

**Comment by Feezyn** [comment]
Erro ao realizar o delete:

![image](https://user-images.githubusercontent.com/55442405/197066000-bea32208-d20c-439c-8629-ae383963acc3.png)

**Comment by valdosouza** [comment]
As operações de Delete ser escritas no aplicativo , mas o endPoint não vai tratar agora.
Muitos de exclusão devem ser tratados, possivelmente serão desativados devido a dependencias.
Só reforço aqui que no aplicativo a chamada deve ocorrer.
Neste momento estou pensando em retornar algo como "Em desenvolvimento"

**Comment by Feezyn** [comment]
(HEAD -> feature/cadastro-estoque, origin/feature/cadastro-estoque) Cadastro Stock/Estoque - Registro #9
